# Generated by Django 2.2.4 on 2019-10-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
